### ISSUE TITLE
直接提示手机根目录下未找到question.txt

### ISSUE THREAD

**Issue by enterlet** [wangwang-code/Study_hamibot#3]
20220429的study.js日志如下
![1](https://user-images.githubusercontent.com/21063655/166107193-0555c1c1-898b-4662-9d46-2a87be7f69c2.png)
只能退回20220428的study.js，但是四人赛后需要手动返回主页
![2](https://user-images.githubusercontent.com/21063655/166107202-36227db7-cb30-41ac-a539-0431597a353d.png)

**Comment by enterlet** [comment]
好像不止四人赛也会出现等待加载出主页
![3](https://user-images.githubusercontent.com/21063655/166915923-b23608b8-e7b4-462a-b508-d28f779823e8.png)

**Comment by Jimlu-666** [comment]
第一次运行，或者更新了脚本，需要强制更新题库，运行的时候有提示，手动点击是，有两个提示框

**Comment by enterlet** [comment]
@Jimlu-666 原来是这样。。。之前没有强制更新题库都没事的，所以还都不知道可以手动点击来强制更新

想问下questionbank.db是放在哪儿的呀，因为我连jsdelivr不是很稳，所以想手动下载替换

我只知道question.txt是放在根目录
